# Generates obj/AppVersion.g.cs from version.txt so the app, the installer and
# the manifest can never disagree about the version number.
# ASCII-only (Windows PowerShell 5.1 reads .ps1 as ANSI without a BOM).
param(
    [string]$Root = (Split-Path -Parent $MyInvocation.MyCommand.Path)
)

$versionFile = Join-Path $Root 'version.txt'
if (-not (Test-Path $versionFile)) { throw "version.txt not found in $Root" }
$short = (Get-Content $versionFile -First 1).Trim()
if ($short -notmatch '^\d+\.\d+\.\d+$') { throw "version.txt must look like 1.2.3, got '$short'" }
$full = "$short.0"

$template = @'
// GENERATED by gen-version.ps1 from version.txt - do not edit by hand.
// Source of truth: version.txt (@SHORT@)
using System.Reflection;

[assembly: AssemblyVersion("@FULL@")]
[assembly: AssemblyFileVersion("@FULL@")]
[assembly: AssemblyInformationalVersion("@SHORT@")]
[assembly: AssemblyTitle("Caffeine")]
[assembly: AssemblyProduct("Caffeine")]

namespace Caffeine
{
    internal static class AppVersion
    {
        internal static readonly string Full = "@FULL@";
        internal static readonly string Short = "@SHORT@";
    }
}
'@

$content = $template.Replace('@SHORT@', $short).Replace('@FULL@', $full)

$objDir = Join-Path $Root 'obj'
New-Item -ItemType Directory -Force -Path $objDir | Out-Null
$genFile = Join-Path $objDir 'AppVersion.g.cs'

# UTF-8 without BOM: csc reads it via /codepage:65001
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($genFile, $content, $utf8)

# keep the manifest identity in sync too
$manifest = Join-Path $Root 'src\app.manifest'
if (Test-Path $manifest) {
    $m = [System.IO.File]::ReadAllText($manifest, [System.Text.Encoding]::UTF8)
    $m2 = [System.Text.RegularExpressions.Regex]::Replace(
        $m, '<assemblyIdentity version="[^"]*"',
        ('<assemblyIdentity version="' + $full + '"'))
    if ($m2 -ne $m) { [System.IO.File]::WriteAllText($manifest, $m2, $utf8) }
}

Write-Host "version $short (assembly $full) -> $genFile"
